//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputManager"",
    ""maps"": [
        {
            ""name"": ""Play"",
            ""id"": ""3b86c1cd-fa8e-45ce-abc3-46f96adca269"",
            ""actions"": [
                {
                    ""name"": ""PullerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""65bdef76-55de-4717-a600-237fdb2ead6e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PullerAttack"",
                    ""type"": ""Button"",
                    ""id"": ""662ca5e4-b062-4058-80ad-ec38c4ef2063"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PullerDash"",
                    ""type"": ""Button"",
                    ""id"": ""2362b20a-6e2e-446d-aa3a-0b203c03ba38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PusherMovement"",
                    ""type"": ""Value"",
                    ""id"": ""e102eceb-e14d-49c9-a2a9-d305ea939be6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PusherAttack"",
                    ""type"": ""Button"",
                    ""id"": ""e003d15a-7316-4d9f-a273-928043d124d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PusherDash"",
                    ""type"": ""Button"",
                    ""id"": ""691c4627-07b7-4db9-860c-936c1984f182"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f436036e-6882-48b8-a742-921aa7c1e0ab"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""55fe9002-626d-43f0-9a17-be50f093ea0b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2a8619af-7b16-4d81-bb5e-9ca47a296b72"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3adb5549-1f35-4103-98ed-c6248d4ae12e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5e56c8a8-8bfe-425f-ba0e-d74e2970b64b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f23148e4-fc7b-41ce-b9ce-743d858ab3a3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4715485e-64a0-40c6-869a-4f9b216dda50"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e1465f34-4c71-4632-9a23-7f221358ed3f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0c213faf-6921-4312-8767-9fb004382396"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""54efaaad-65f4-4d43-9a0d-c8ac572d7760"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""be8de6bf-a067-4344-aac5-54a80adf2509"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""299568b8-65f1-460e-83ae-75339195294d"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PusherDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bb4c492-f365-4371-bf34-12d8c82970ec"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c82e68f-01ba-4b9b-9294-6e0c60a1d5f3"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PullerDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Navigation"",
            ""id"": ""f8d22f81-9bdf-4dc7-9e5c-8c0c0c45d1d9"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""034b971b-8767-4834-a781-52d8ea904ae2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""32888813-5996-4df2-ada8-e1c5f67d9dea"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Play
        m_Play = asset.FindActionMap("Play", throwIfNotFound: true);
        m_Play_PullerMovement = m_Play.FindAction("PullerMovement", throwIfNotFound: true);
        m_Play_PullerAttack = m_Play.FindAction("PullerAttack", throwIfNotFound: true);
        m_Play_PullerDash = m_Play.FindAction("PullerDash", throwIfNotFound: true);
        m_Play_PusherMovement = m_Play.FindAction("PusherMovement", throwIfNotFound: true);
        m_Play_PusherAttack = m_Play.FindAction("PusherAttack", throwIfNotFound: true);
        m_Play_PusherDash = m_Play.FindAction("PusherDash", throwIfNotFound: true);
        // Navigation
        m_Navigation = asset.FindActionMap("Navigation", throwIfNotFound: true);
        m_Navigation_Newaction = m_Navigation.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Play
    private readonly InputActionMap m_Play;
    private List<IPlayActions> m_PlayActionsCallbackInterfaces = new List<IPlayActions>();
    private readonly InputAction m_Play_PullerMovement;
    private readonly InputAction m_Play_PullerAttack;
    private readonly InputAction m_Play_PullerDash;
    private readonly InputAction m_Play_PusherMovement;
    private readonly InputAction m_Play_PusherAttack;
    private readonly InputAction m_Play_PusherDash;
    public struct PlayActions
    {
        private @InputManager m_Wrapper;
        public PlayActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @PullerMovement => m_Wrapper.m_Play_PullerMovement;
        public InputAction @PullerAttack => m_Wrapper.m_Play_PullerAttack;
        public InputAction @PullerDash => m_Wrapper.m_Play_PullerDash;
        public InputAction @PusherMovement => m_Wrapper.m_Play_PusherMovement;
        public InputAction @PusherAttack => m_Wrapper.m_Play_PusherAttack;
        public InputAction @PusherDash => m_Wrapper.m_Play_PusherDash;
        public InputActionMap Get() { return m_Wrapper.m_Play; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayActions set) { return set.Get(); }
        public void AddCallbacks(IPlayActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayActionsCallbackInterfaces.Add(instance);
            @PullerMovement.started += instance.OnPullerMovement;
            @PullerMovement.performed += instance.OnPullerMovement;
            @PullerMovement.canceled += instance.OnPullerMovement;
            @PullerAttack.started += instance.OnPullerAttack;
            @PullerAttack.performed += instance.OnPullerAttack;
            @PullerAttack.canceled += instance.OnPullerAttack;
            @PullerDash.started += instance.OnPullerDash;
            @PullerDash.performed += instance.OnPullerDash;
            @PullerDash.canceled += instance.OnPullerDash;
            @PusherMovement.started += instance.OnPusherMovement;
            @PusherMovement.performed += instance.OnPusherMovement;
            @PusherMovement.canceled += instance.OnPusherMovement;
            @PusherAttack.started += instance.OnPusherAttack;
            @PusherAttack.performed += instance.OnPusherAttack;
            @PusherAttack.canceled += instance.OnPusherAttack;
            @PusherDash.started += instance.OnPusherDash;
            @PusherDash.performed += instance.OnPusherDash;
            @PusherDash.canceled += instance.OnPusherDash;
        }

        private void UnregisterCallbacks(IPlayActions instance)
        {
            @PullerMovement.started -= instance.OnPullerMovement;
            @PullerMovement.performed -= instance.OnPullerMovement;
            @PullerMovement.canceled -= instance.OnPullerMovement;
            @PullerAttack.started -= instance.OnPullerAttack;
            @PullerAttack.performed -= instance.OnPullerAttack;
            @PullerAttack.canceled -= instance.OnPullerAttack;
            @PullerDash.started -= instance.OnPullerDash;
            @PullerDash.performed -= instance.OnPullerDash;
            @PullerDash.canceled -= instance.OnPullerDash;
            @PusherMovement.started -= instance.OnPusherMovement;
            @PusherMovement.performed -= instance.OnPusherMovement;
            @PusherMovement.canceled -= instance.OnPusherMovement;
            @PusherAttack.started -= instance.OnPusherAttack;
            @PusherAttack.performed -= instance.OnPusherAttack;
            @PusherAttack.canceled -= instance.OnPusherAttack;
            @PusherDash.started -= instance.OnPusherDash;
            @PusherDash.performed -= instance.OnPusherDash;
            @PusherDash.canceled -= instance.OnPusherDash;
        }

        public void RemoveCallbacks(IPlayActions instance)
        {
            if (m_Wrapper.m_PlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayActions @Play => new PlayActions(this);

    // Navigation
    private readonly InputActionMap m_Navigation;
    private List<INavigationActions> m_NavigationActionsCallbackInterfaces = new List<INavigationActions>();
    private readonly InputAction m_Navigation_Newaction;
    public struct NavigationActions
    {
        private @InputManager m_Wrapper;
        public NavigationActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Navigation_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Navigation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NavigationActions set) { return set.Get(); }
        public void AddCallbacks(INavigationActions instance)
        {
            if (instance == null || m_Wrapper.m_NavigationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NavigationActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(INavigationActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(INavigationActions instance)
        {
            if (m_Wrapper.m_NavigationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INavigationActions instance)
        {
            foreach (var item in m_Wrapper.m_NavigationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NavigationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NavigationActions @Navigation => new NavigationActions(this);
    public interface IPlayActions
    {
        void OnPullerMovement(InputAction.CallbackContext context);
        void OnPullerAttack(InputAction.CallbackContext context);
        void OnPullerDash(InputAction.CallbackContext context);
        void OnPusherMovement(InputAction.CallbackContext context);
        void OnPusherAttack(InputAction.CallbackContext context);
        void OnPusherDash(InputAction.CallbackContext context);
    }
    public interface INavigationActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
